name: Set Repositories State Property

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'  # Run this workflow every day at midnight

jobs:
  call-stale-repos:
    name: 'Call stale-repos'
    uses: ch-robinson-internal-test/AppSec-Workflows/.github/workflows/stale-repos.yml@main
    with:
      period: 365
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
  process-stale-repos-output:
    name: 'Process stale-repos output'
    needs: call-stale-repos
    runs-on: ubuntu-latest
    steps:
    - name: Extract URLs of Stale Repos
      id: extract-urls
      run: |
        jsonString='${{ needs.call-stale-repos.outputs.stale_repos }}'
        urls=$(echo "$jsonString" | grep -oP '(?<=url: )[^\,]*')
        echo "urls=$urls" >> $GITHUB_OUTPUT

    - name: Set Repo Property (State=Stale)
      run: |
        echo ${{ steps.extract-urls.outputs.urls }}
        IFS=' ' read -r -a urls <<< "${{ steps.extract-urls.outputs.urls }}"
        for url in $urls; do
          repo=$(echo "$url" | cut -d'/' -f 4-)
          echo $repo         
        done

        #urls=${{ steps.extract-urls.outputs.urls }}
       # response=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo")
       # echo "$response"
