name: Set Repositories State Property

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'  # Run this workflow every day at midnight

jobs:
  call-stale-repos:
    name: 'Call stale-repos'
    uses: ch-robinson-internal-test/AppSec-Workflows/.github/workflows/stale-repos.yml@main
    with:
      period: 1200
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
  process-stale-repos-output:
    name: 'Process stale-repos output'
    needs: call-stale-repos
    runs-on: ubuntu-latest
    steps:
    - name: Extract URLs and Set Stale Repos
      id: extract-urls
      run: |
        jsonString='${{ needs.call-stale-repos.outputs.stale_repos }}'
        urls=$(echo "$jsonString" | grep -oP '(?<=url: )[^\,]*')
        for url in $urls; do
          repo=$(echo "$url" | cut -d'/' -f 4-)
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ch-robinson-internal-test/$repo/properties/values \
            -d '{"properties":[{"property_name":"state","value":"stale"}]}'
        done

      #for url in $urls; do
      #  repo=$(echo "$url" | cut -d'/' -f 4-)
      #  response=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo")
      #  echo "$response"
      #done