name: Set Repositories State Property

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'  # Run this workflow every day at midnight

jobs:
  call-stale-repo-identifier:
      uses: ch-robinson-internal-test/AppSec-Workflows/.github/workflows/stale-repos.yml@main
      #secrets:
      #  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  #set-repo-state-property:
  #  runs-on: ubuntu-latest
  #  steps:
  
  #    - name: Checkout stale-repos
  #      uses: ch-robinson-internal-test/checkout@main
  #      with:
  #        repository: ch-robinson-internal-test/stale-repos

#      - name: Run stale-repos
#        id: stale-repos
#        run: |
#          # Run the stale-repos script and capture the output
#          output=$(./stale-repos)
#          echo "$output"
#          echo "::set-output name=stale_repos::$output"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
