name: Set Repositories State Property

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'  # Run this workflow every day at midnight

jobs:
  call-stale-repos:
    name: 'Call stale-repos'
    uses: ch-robinson-internal-test/AppSec-Workflows/.github/workflows/stale-repos.yml@main
    with:
      period: 365
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
  process-stale-repos-output:
    name: 'Process stale-repos output'
    needs: call-stale-repos
    runs-on: ubuntu-latest
    steps:
    - name: Echo stale-repos output
      run: echo ${{ needs.call-stale-repos.outputs.stale_repos }}


  #set-repo-state-property:
  #  runs-on: ubuntu-latest
  #  steps:
  
  #    - name: Checkout stale-repos
  #      uses: ch-robinson-internal-test/checkout@main
  #      with:
  #        repository: ch-robinson-internal-test/stale-repos

#      - name: Run stale-repos
#        id: stale-repos
#        run: |
#          # Run the stale-repos script and capture the output
#          output=$(./stale-repos)
#          echo "$output"
#          echo "::set-output name=stale_repos::$output"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
