name: stale repo identifier

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - uses: ch-robinson-internal-test/checkout@main

    - name: Run stale_repos tool
      uses: ch-robinson-internal-test/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: "ch-robinson-internal-test"
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365

    # This next step updates an existing issue. If you want a new issue every time, remove this step and remove the `issue-number: ${{ env.issue_number }}` line below.
    #- name: Check for the stale report issue
    #  run: |
    #    ISSUE_NUMBER=$(gh search issues "Stale repository report" --match title --json number --jq ".[0].number")
    #    echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"
    #  env:
    #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Create issue
    #  uses: peter-evans/create-issue-from-file@v4
    #  with:
    #    issue-number: ${{ env.issue_number }}
    #    title: Stale repository report
    #    content-filepath: ./stale_repos.md
    #    assignees: APOB83
    #    token: ${{ secrets.GITHUB_TOKEN }}
