name: Stale Repo Finder

on:
  workflow_call:
    inputs:
      period:
        required: true
        type: number
        description: Threshold period for inactivity (in days)
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      stale_repos:
        description: "List of stale repositories"
        value: ${{ jobs.find-stale-repos.outputs.stale_repos }}

jobs:
  find-stale-repos:
    name: Find Stale Repos
    runs-on: ubuntu-latest
    outputs:
      stale_repos: ${{ steps.output.outputs.stale_repos }}

    steps:
    - name: Validate inputs
      run: |
        if (( ${{ inputs.period }} <= 0 )); then
          echo "Error: period must be a positive number"
          exit 1
        fi

    - name: Checkout
      uses: ch-robinson-internal-test/checkout@main

    - name: Run stale-repos
      id: stale-repos
      uses: ch-robinson-internal-test/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: "ch-robinson-internal-test"
        INACTIVE_DAYS: ${{ inputs.period }}
      continue-on-error: true
    
    - name: Check stale-repos output
      run: |
        if [[ -z "${{ steps.stale-repos.outputs.inactiveRepos }}" ]]; then
          echo "Error: stale-repos did not produce any output"
          exit 1
        fi
    
    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"

    - name: Set output
      id: output
      run: echo "stale_repos=${{ steps.stale-repos.outputs.inactiveRepos }}" >> $GITHUB_OUTPUT