name: stale repo identifier

on:
  workflow_call:
    inputs:
      period:
        required: true
        type: number
        description: Threshold period for inactivity (in days)
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      stale_repos:
        description: "List of stale repositories"
        value: ${{ jobs.build.outputs.stale_repos }}

jobs:
  build:
    name: Find Stale Repos
    runs-on: ubuntu-latest
    outputs:
      stale_repos: ${{ steps.output.outputs.stale_repos }}

    steps:
    - name: Checkout
      uses: ch-robinson-internal-test/checkout@main

    - name: Run stale-repos
      id: stale-repos
      uses: ch-robinson-internal-test/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: "ch-robinson-internal-test"
        INACTIVE_DAYS: ${{ inputs.period }}
    
    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"

    - name: Set output
      id: output
      run: |
        jsonString = ${{ steps.stale-repos.outputs.inactiveRepos }}
        formattedJson = JSON.stringify(jsonString)
        echo "stale_repos=${formattedJson}" >> $GITHUB_OUTPUT
      #run: echo "stale_repos=${{ steps.stale-repos.outputs.inactiveRepos }}" >> $GITHUB_OUTPUT