name: stale repo identifier

on:
  workflow_call:
    inputs:
      period:
        required: true
        type: number
        description: Threshold period for inactivity (in days)
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      stale_repos:
        description: "List of stale repositories"
        value: ${{ jobs.build.outputs.stale_repos }}

jobs:
  build:
    name: Find Stale Repos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: ch-robinson-internal-test/checkout@main

    - name: Run stale-repos
      id: stale-repos
      uses: ch-robinson-internal-test/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: "ch-robinson-internal-test"
        INACTIVE_DAYS: ${{ inputs.period }}
    
    - name: Set output
      id: output
      run: echo "::set-output name=stale_repos::${{ steps.stale-repos.outputs.inactiveRepos }}"