name: stale repo identifier

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      stale_repos:
        description: "List of stale repositories"
        value: ${{ jobs.build.outputs.stale_repos }}

jobs:
  build:
    name: Find Stale Repos
    runs-on: ubuntu-latest

    steps:
    - uses: ch-robinson-internal-test/checkout@main

    - name: Run stale_repos tool
      id: stale-repos
      uses: ch-robinson-internal-test/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: "ch-robinson-internal-test"
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365

    - name: Display output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"

        
    #- name: Set output
    #  id: output
    #  run: |
    #    output=$(cat stale_repos.txt)
    #    echo "::set-output name=stale_repos::$output"
